
package fourteen;

import java.applet.Applet;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

public class SimpleKey extends Applet implements KeyListener
{
            String msg = "";
            int X = 10, Y = 20; // output coordinates
            public void init()
            {
                        addKeyListener(this);
            }

           public void keyPressed(KeyEvent ke) 
            {
                        showStatus("Key Pressed");
            }
           public void keyReleased(KeyEvent ke) 
            {
                        showStatus("Key Released");
            }
           public void keyTyped(KeyEvent ke) 
            {
                        showStatus("Key Typed");
                        msg += ke.getKeyChar();
                        repaint();
            }
           // Display keystrokes.
           public void paint(Graphics g) 
            {
                        g.drawString(msg, X, Y);
            }
}

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
